---
# Workaround for https://github.com/CiscoCloud/mantl/161
- name: install latest device-mapper-libs
  sudo: yes
  yum:
    name: device-mapper-libs
    state: latest
  tags:
    - docker
    - bootstrap
    - lvm

- name: install LVM tools
  sudo: yes
  yum:
    name: lvm2
    state: latest
  tags:
    - docker
    - bootstrap
    - lvm

- name: enable lvmetad service
  sudo: yes
  service:
    name: lvm2-lvmetad
    enabled: yes
    state: started
  tags:
    - docker
    - lvm

- name: install partitioner script
  sudo: yes
  copy:
    src: mantl-storage-setup.py
    dest: /usr/local/bin/mantl-storage-setup
    mode: 0755
  tags:
    - docker
    - lvm

- name: install partitioner service
  sudo: yes
  copy:
    src: mantl-storage-setup.service
    dest: /etc/systemd/system/mantl-storage-setup.service
    mode: 0644
  tags:
    - docker
    - lvm

- name: create directory for volume configs
  sudo: yes
  file:
    state: directory
    path: /etc/mantl/filesystems.d
    mode: 755
  tags:
    - docker
    - lvm

- name: put volume configuration file
  sudo: yes
  template:
    src: mantl-volume-group.conf.j2
    dest: /etc/mantl/filesystems.d/10-volume-group.conf
  tags:
    - docker
    - lvm

- name: enable partitioner service
  sudo: yes
  service:
    name: mantl-storage-setup.service
    enabled: yes
  tags:
    - docker
    - lvm

- name: save volume group name as fact
  set_fact:  volume_group_name="{{ lvm_volume_group_name }}"
  tags:
    - lvm
